version: "3.9"
services:
  postgres:
    container_name: postgres_container_org
    image: postgres:14
    environment:
      POSTGRES_DB: "tg"
      POSTGRES_USER: "tg"
      POSTGRES_PASSWORD: "tg"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../1. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "6444:5432"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tg -d tg"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

networks:
  postgres:
    driver: bridge